### ISSUE TITLE
Suggestions for UI/UX improvements

### ISSUE THREAD

**Issue by palkerecsenyi** [mgs-sports-day/sportsday1.5#1]
**From @tti0**:

Thank you so much for all your work on the website -- it looks modern, professional, and generally brilliant.

There is one bug I have noticed:

On mobile (Firefox on Android), opening the Information page (https://mgs-sportsday.net/#/info) triggers a download of the timetable and map PDFs immediately, as pdfJs is not supported on mobile. I don't think many people use Firefox mobile, and there is no such issue on Google Chrome on Android. It is probably worth checking the situation on Safari/iOS, though.

I have a few suggestions, as follows:

(These are not critical at all, and are merely suggestions. No problem if these don't get implemented)

- On the Forms page (https://mgs-sportsday.net/#/forms), I don't think that it is very obvious that one can click a form name to view its individual page. Should we add a "Click to view form" button (as on the Events page) to each row in the table, or add a note informing people of this functionality?
- On an individual event page (e.g. https://mgs-sportsday.net/#/events/longJump), should we add in a separate column for Record Bonus points?
- On an individual event page, should we add details of the appropriate year group record for that event?
- Are we adding the record summary statistics in a table to the Records page (https://mgs-sportsday.net/#/records)? The API has a method to fetch this.
- Are we going to have a favicon? The one from sportsday1 should be fine, but does need crediting.

Many thanks, and congratulations.

**Comment by palkerecsenyi** [comment]
Thanks for the feedback!

About the PDF bug: yes, I also use Firefox on my phone and this is indeed a strange and annoying problem. I'm not sure if Mozilla have any plans to fix this, but in Chrome it just shows a "tap here to download button" as a replacement. I just tested on iOS and it renders the PDF in-place, albeit in a slightly awkward way as though it were an image. 

The "Download PDF" button provided by our site is still there and that should work on all devices. We _could_ detect Firefox on Android and disable the iframe, but that seems like a dodgy solution and there's no definitive way to detect how a browser will behave should a rendering attempt be made. So I guess we could just leave the Firefox users to suffer?

Here's Safari on my ipad:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/22198767/176725006-bd3aa562-8310-4433-bc30-c1ef94acd6d9.png">

**Comment by palkerecsenyi** [comment]
Suggestion 1 (about Forms page): I agree it's quite hard to see, especially with the Year 7/8 forms which are very short. I think the table isn't _too_ narrow on mobile at the moment, so adding in a button wouldn't hurt.

@gezakerecsenyi could you look at this please? Maybe use an icon if a button with text looks awkward?

**Comment by tti0** [comment]
> Thanks for the feedback!
> 
> About the PDF bug: yes, I also use Firefox on my phone and this is indeed a strange and annoying problem. I'm not sure if Mozilla have any plans to fix this, but in Chrome it just shows a "tap here to download button" as a replacement. I just tested on iOS and it renders the PDF in-place, albeit in a slightly awkward way as though it were an image.
> 
> The "Download PDF" button provided by our site is still there and that should work on all devices. We _could_ detect Firefox on Android and disable the iframe, but that seems like a dodgy solution and there's no definitive way to detect how a browser will behave should a rendering attempt be made. So I guess we could just leave the Firefox users to suffer?
> 
> Here's Safari on my ipad:
> 
> <img alt="image" width="1080" src="https://user-images.githubusercontent.com/22198767/176725006-bd3aa562-8310-4433-bc30-c1ef94acd6d9.png">

I agree; the proportion of students using Firefox on mobile is very small, and will be technically-minded, so will be able to handle downloading files better than the average person. Best to take the pragmatic approach and leave as-is.

**Comment by palkerecsenyi** [comment]
Suggestions 2, 3 and 4 (about individual events page and the records page):

I'm not sure whether adding a column to the table would make it more confusing or less confusing. It would help clear up _where_ the extra points are coming from but it would also add a bit of complexity to what is already a fairly complicated (and wide) table. What are your thoughts on this?

But I definitely agree with the record summary at the bottom of the page, that was a useful and interesting insight we had in the last website ([here](https://github.com/mgs-sports-day/sportsday1/blob/master/views/event.htm#L107-L138) for reference). We'll add that in! Same goes for the [record summary stats](https://github.com/mgs-sports-day/sportsday1/blob/master/views/records.htm#L12-L32), that would be a very useful stat to look at on the day.

**Comment by palkerecsenyi** [comment]
@gezakerecsenyi could you also add the favicon please?

The icon is [here](https://raw.githubusercontent.com/mgs-sports-day/sportsday1/master/favicon.ico) and the attribution is [here](https://github.com/mgs-sports-day/sportsday1/blob/master/views/about.htm#L138).
